CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  depositor_name TEXT NOT NULL,
  status TEXT DEFAULT 'PENDING', -- PENDING / APPROVED / REJECTED
  access_token TEXT,
  approved_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
